// <auto-generated />
using System;
using CosmeticSalon.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmeticSalon.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(CosmeticSalonDbContext))]
    [Migration("20250403164635_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CosmeticSalon.Infrastructure.Treatments.Models.TreatmentDbModel", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("CosmeticSalon.Infrastructure.Treatments.Models.TreatmentUserDbModel", b =>
                {
                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecordId");

                    b.ToTable("TreatmentUsers");
                });

            modelBuilder.Entity("CosmeticSalon.Infrastructure.Treatments.Models.TreatmentUserDbModel", b =>
                {
                    b.HasOne("CosmeticSalon.Infrastructure.Treatments.Models.TreatmentDbModel", "Treatment")
                        .WithMany("TreatmentUsers")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("CosmeticSalon.Infrastructure.Treatments.Models.TreatmentDbModel", b =>
                {
                    b.Navigation("TreatmentUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
